20:19:43 **** Clean-only build of configuration Debug for project src ****
make clean 
Cannot run program "make": Launching failed

Error: Program "make" not found in PATH
PATH=[C:/Program Files (x86)/Atollic/TrueSTUDIO for STM32 9.3.0/ide/jre/bin/client;C:/Program Files (x86)/Atollic/TrueSTUDIO for STM32 9.3.0/ide/jre/bin;C:/Program Files (x86)/Atollic/TrueSTUDIO for STM32 9.3.0/ide/jre/lib/i386;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\ia32\compiler;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\MATLAB\R2017a\runtime\win64;C:\Program Files\MATLAB\R2017a\bin;C:\Program Files\Java\jdk1.8.0_101\bin;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\nodejs\;C:\Users\kulie\AppData\Local\Programs\Python\Python36;C:\Program Files\Git\cmd;C:\Program Files\Git LFS;C:\Program Files\PuTTY\;C:\Program Files (x86)\ChucK\/bin;C:\Program Files (x86)\IVI Foundation\VISA\WinNT\Bin\;C:\Program Files\IVI Foundation\VISA\Win64\Bin\;C:\Users\kulie\AppData\Local\Programs\Python\Python36\Scripts\;C:\Users\kulie\AppData\Local\Programs\Python\Python36\;C:\Users\kulie\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Python 3.6;C:\Users\kulie\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\kulie\AppData\Local\GitHubDesktop\bin;C:\Users\kulie\AppData\Local\Android\sdk\platform-tools;C:\Users\kulie\AppData\Roaming\npm;C:\Users\kulie\Documents\##PROGRAMACAO##\Linx Challenge\vitrine-de-itens-recomendados\node_modules\heroku;C:\Program Files\Git LFS;C:\Modeltech_pe_edu_10.4a\win32pe_edu;C:\Users\kulie\AppData\Local\Microsoft\WindowsApps;;C:\Program Files (x86)\Atollic\TrueSTUDIO for STM32 9.3.0;]

**** Build of configuration Debug for project src ****

Nothing to build for project src
